# Generated by Django 5.2 on 2025-05-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conference",
            options={"ordering": ["-year"]},
        ),
        migrations.AddField(
            model_name="conference",
            name="year",
            field=models.PositiveIntegerField(default=2018, unique=True),
            preserve_default=False,
        ),
    ]
