# Generated by Django 5.2 on 2025-05-04 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0002_alter_conference_options_conference_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("affiliation", models.CharField(blank=True, max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="people/"),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="conference",
            name="current_attendees",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="max_attendees",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="registration_deadline",
        ),
        migrations.RemoveField(
            model_name="conference",
            name="start_date",
        ),
        migrations.AddField(
            model_name="conference",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conference",
            name="venue",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ImportantDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("is_deadline", models.BooleanField(default=False)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_dates",
                        to="conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="conference",
            name="general_chairs",
            field=models.ManyToManyField(
                blank=True, related_name="general_chairs", to="conference.person"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="organizers",
            field=models.ManyToManyField(
                blank=True, related_name="organizers", to="conference.person"
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="program_chairs",
            field=models.ManyToManyField(
                blank=True, related_name="program_chairs", to="conference.person"
            ),
        ),
        migrations.CreateModel(
            name="Speaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_keynote", models.BooleanField(default=False)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speakers",
                        to="conference.conference",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="conference.person",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
        migrations.CreateModel(
            name="AgendaItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_break", models.BooleanField(default=False)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agenda_items",
                        to="conference.conference",
                    ),
                ),
                (
                    "speakers",
                    models.ManyToManyField(blank=True, to="conference.speaker"),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
