# Generated by Django 5.2 on 2025-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0003_person_remove_conference_current_attendees_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="speakers/"),
        ),
    ]
