# Generated by Django 5.2 on 2025-06-05 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0004_speaker_profile_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ["person__name"]},
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="description",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="is_keynote",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="time",
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="title",
        ),
    ]
