# Generated by Django 5.2 on 2025-06-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "conference",
            "0005_alter_speaker_options_remove_speaker_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speaker",
            options={"ordering": ["last_name", "first_name"]},
        ),
        migrations.RemoveField(
            model_name="speaker",
            name="person",
        ),
        migrations.AddField(
            model_name="speaker",
            name="first_name",
            field=models.CharField(default="bruh", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speaker",
            name="last_name",
            field=models.CharField(default="bruhson", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="speaker",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
