# Generated by Django 5.2 on 2025-06-05 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0007_remove_conference_organizers_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="agendaitem",
            options={"ordering": ["time_start"]},
        ),
        migrations.RenameField(
            model_name="agendaitem",
            old_name="time",
            new_name="time_end",
        ),
        migrations.AddField(
            model_name="agendaitem",
            name="time_start",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
