# Generated by Django 5.2 on 2025-06-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0008_alter_agendaitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendaitem",
            name="icon",
            field=models.CharField(
                choices=[
                    ("keynote", "Keynote"),
                    ("break", "Break"),
                    ("gathering", "Gathering"),
                    ("paper", "Paper"),
                    ("drinks", "Drinks"),
                ],
                default="keynote",
                max_length=20,
            ),
        ),
    ]
