# Generated by Django 5.2 on 2025-06-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0009_alter_agendaitem_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="organizers/"),
                ),
            ],
        ),
    ]
