# Generated by Django 5.2 on 2025-06-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0010_organizer"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="call_for_papers",
            field=models.TextField(
                blank=True, help_text="Call for papers content (supports markdown)"
            ),
        ),
        migrations.AlterField(
            model_name="conference",
            name="description",
            field=models.TextField(
                blank=True, help_text="Main conference description (supports markdown)"
            ),
        ),
    ]
