# Generated by Django 5.2 on 2025-06-06 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0011_conference_call_for_papers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConferenceRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="e.g., Prof., Dr.", max_length=200
                    ),
                ),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("general_chair", "General Chair"),
                            ("program_chair", "Program Chair"),
                            ("organizer", "Organizer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "affiliation",
                    models.CharField(
                        blank=True,
                        help_text="University or organization",
                        max_length=300,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order within role type"
                    ),
                ),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="conference.conference",
                    ),
                ),
            ],
            options={
                "ordering": ["role_type", "order", "last_name"],
            },
        ),
    ]
