# Generated by Django 5.2 on 2025-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0012_conferencerole"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="submission_button_link",
            field=models.URLField(
                blank=True,
                help_text="URL for the submission button (leave empty to disable link)",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="submission_button_text",
            field=models.CharField(
                blank=True,
                default="MANUSCRIPT SUBMISSION CLOSED",
                help_text="Text displayed on the submission button",
                max_length=200,
            ),
        ),
    ]
