# Generated by Django 5.2 on 2025-06-06 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0014_importantdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="hero_subtitle",
            field=models.TextField(
                blank=True,
                help_text="Subtitle with date, location, etc. Supports line breaks with <br>",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="hero_title",
            field=models.CharField(
                blank=True,
                help_text="Main title in hero section (defaults to conference title if empty)",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="livestream_label",
            field=models.CharField(
                blank=True,
                default="Livestream",
                help_text="Label above the video",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="livestream_video_url",
            field=models.URLField(
                blank=True,
                help_text="YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="show_livestream",
            field=models.BooleanField(
                default=True, help_text="Show/hide the livestream video section"
            ),
        ),
    ]
