# Generated by Django 5.2 on 2025-06-06 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0015_conference_hero_subtitle_conference_hero_title_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizer",
            options={"ordering": ["order", "name"]},
        ),
        migrations.AddField(
            model_name="organizer",
            name="conference",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organizers",
                to="conference.conference",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organizer",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Display order"),
        ),
    ]
