# Generated by Django 5.2 on 2025-06-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0016_alter_organizer_options_organizer_conference_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="map_address",
            field=models.TextField(
                blank=True,
                help_text="Detailed address shown below venue name (supports line breaks with <br>)",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="map_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Google Maps embed URL (get from Google Maps > Share > Embed)",
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="map_venue_name",
            field=models.CharField(
                blank=True,
                help_text="Large venue name displayed on map (supports line breaks with <br>)",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="conference",
            name="show_map",
            field=models.BooleanField(
                default=True, help_text="Show/hide the map section"
            ),
        ),
    ]
