# Generated by Django 5.2 on 2025-06-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0019_copy_title_to_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="agendaitem",
            name="title",
        ),
        migrations.AlterField(
            model_name="agendaitem",
            name="content",
            field=models.TextField(
                help_text="Agenda item content (supports markdown for lists, formatting, etc.)"
            ),
        ),
    ]
