# Generated by Django 5.2 on 2025-06-06 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0020_remove_title_from_agenda"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(
                        blank=True, help_text="Main organization name", max_length=200
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline or description",
                        max_length=300,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Contact email address", max_length=254
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Contact phone number", max_length=50
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Physical address (supports line breaks with <br>)",
                    ),
                ),
                (
                    "twitter_url",
                    models.URLField(blank=True, help_text="Twitter profile URL"),
                ),
                (
                    "linkedin_url",
                    models.URLField(blank=True, help_text="LinkedIn profile URL"),
                ),
                (
                    "github_url",
                    models.URLField(blank=True, help_text="GitHub profile URL"),
                ),
                (
                    "facebook_url",
                    models.URLField(blank=True, help_text="Facebook profile URL"),
                ),
                (
                    "youtube_url",
                    models.URLField(blank=True, help_text="YouTube channel URL"),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        help_text="Copyright notice (year will be auto-added)",
                        max_length=200,
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        blank=True,
                        help_text="Additional footer content (supports markdown)",
                    ),
                ),
                (
                    "show_social_links",
                    models.BooleanField(
                        default=True, help_text="Show/hide social media links"
                    ),
                ),
                (
                    "show_contact_info",
                    models.BooleanField(
                        default=True, help_text="Show/hide contact information"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Footer Settings",
                "verbose_name_plural": "Footer Settings",
            },
        ),
    ]
