# Generated by Django 5.2 on 2025-06-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0021_add_footer_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="speaker",
            name="link_url",
            field=models.URLField(
                blank=True,
                help_text="Link for speaker profile (personal website, LinkedIn, etc.)",
            ),
        ),
    ]
